mod dashboard;
mod markdown;
mod panels;
pub(crate) mod ui;
mod views;
mod work_digest;

pub(crate) use dashboard::DashboardDocumentData;
pub(crate) use dashboard::dashboard_document;
pub(crate) use views::DocumentData;
pub(crate) use views::PlanPresentation;
pub(crate) use views::approval_fragment;
pub(crate) use views::bootstrap_document;
pub(crate) use views::document;
pub(crate) use views::item_fragment;
pub(crate) use views::item_fragment_with_plan_presentation;
pub(crate) use views::thread_title;
pub(crate) use views::transcript_fragment;
pub(crate) use work_digest::activity_row;
pub(crate) use work_digest::is_activity;
pub(crate) use work_digest::is_visible_activity;
pub(crate) use work_digest::work_digest;
